// Generated by Wrangler on Thu Aug 22 2024 16:19:58 GMT+0800 (Taipei Standard Time)
// by running `wrangler types`

interface Env {
  API_HOST: string
  AUTH_KEY_SECRET: string
  WALLPAPERS_BUCKET: R2Bucket
  WALLPAPERS_DB: D1Database
}
